services:
  - type: web
    name: jobportal
    runtime: node
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-flash-latest
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: "*"
      - key: NODE_ENV
        value: production
